# Site settings
author: Amber Kerawala
title: Scientist to Developer
header-img: img/home-bg.png
email: amber_kerawala@berkeley.edu
copyright_name: Amber Kerawala
description: > # this means to ignore newlines until "baseurl:"
  My Coding Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  amkera

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
